source:
  name: city_events
  connector: http
  configuration:
    base_url: https://api.events.example.com
    api_key: ${EVENT_API_KEY}
    start_date: "2023-01-01T00:00:00Z"
    city: YOUR_CITY
  incremental_sync:
    cursor_field: updated_at
    replication_method: incremental
