destination:
  name: warehouse
  connector: snowflake
  configuration:
    account: ${SNOWFLAKE_ACCOUNT}
    username: ${SNOWFLAKE_USER}
    password: ${SNOWFLAKE_PASSWORD}
    database: ${SNOWFLAKE_DATABASE}
    schema: ${SNOWFLAKE_SCHEMA}
    warehouse: ${SNOWFLAKE_WAREHOUSE}
    role: ${SNOWFLAKE_ROLE}
  incremental_sync:
    destination_sync_mode: append_dedup
    primary_key: id
    cursor_field: timestamp
