source:
  name: weather_data
  connector: http
  configuration:
    base_url: https://api.openweathermap.org/data/2.5/weather
    api_key: ${OPENWEATHER_API_KEY}
    start_date: "2023-01-01T00:00:00Z"
    city: Sydney,AU
  incremental_sync:
    cursor_field: dt
    replication_method: incremental
