---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: foot-traffic-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foot-traffic
  template:
    metadata:
      labels:
        app: foot-traffic
    spec:
      containers:
        - name: foot-traffic
          image: ${IMAGE}
          env:
            - name: BENTOML_PORT
              value: "3000"
          ports:
            - name: http
              containerPort: 3000
            - name: metrics
              containerPort: 3001
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /livez
              port: http
  strategy:
    canary:
      steps:
        - setWeight: 5
        - pause: {duration: 30}
        - setWeight: 25
        - pause: {duration: 30}
        - setWeight: 100
