groups:
  - name: training-serving-alerts
    rules:
      - alert: TrainingServiceDown
        expr: up{job="training"} == 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Training service is down"
      - alert: ServingServiceDown
        expr: up{job="serving"} == 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Serving service is down"
