global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'training'
    static_configs:
      - targets: ['training:8000']
  - job_name: 'serving'
    static_configs:
      - targets: ['serving:8000']

rule_files:
  - alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
