---
name: Deployment

'on':
  push:
    branches: [main]
  pull_request: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0
      - name: Validate Kubernetes manifests
        run: |
          kubectl apply --dry-run=client -f k8s/ray-cluster.yaml
          kubectl apply --dry-run=client -f k8s/argo-rollout.yaml
