name: Rollout

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
      ROLLOUT_NAME: ${{ vars.ROLLOUT_NAME }}
      NAMESPACE: ${{ vars.ROLLOUT_NAMESPACE }}
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3

      - name: Install Argo Rollouts kubectl plugin
        run: |
          curl -L https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64.tar.gz -o kubectl-argo-rollouts.tgz
          tar -zxvf kubectl-argo-rollouts.tgz
          sudo mv kubectl-argo-rollouts /usr/local/bin/

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Update rollout manifest
        run: |
          sed -i "s@image:.*@image: $IMAGE@" k8s/argo-rollout.yaml

      - name: Apply rollout
        run: kubectl apply -f k8s/argo-rollout.yaml -n $NAMESPACE

      - name: Promote rollout
        run: kubectl argo rollouts promote $ROLLOUT_NAME -n $NAMESPACE
